### nf-core/scrnaseq

The `nf-core/scrnaseq` pipeline was developed by the nf-core community as a best-practice workflow for the initial processing of single cell RNA sequencing data from barcode-based protocols, including 10X, DropSeq and SmartSeq.

The main inputs to the pipeline are FASTQ files containing the unfiltered and basecalled reads generated by the sequencer. For 10X data, these reads are passed through 10X's `cellranger` software; alternative tools such as `STARSolo`, `Kallisto` and `Salmon-Alevin` are also available for both 10X data as well as DropSeq and SmartSeq data. The output of the pipeline in all cases is a count matrix containing the number of sequencing reads that aligned to each gene or transcript in each cell.

#### Inputs

At the very minimum, the `scrnaseq` pipeline requires for each sample:

- A sample name
- Two paired FASTQ files

Barcoded single cell RNA sequencing protocols typically rely on a paired-end sequencing platform where a DNA fragment will be read from both ends. For the 10X protocol, the first read ("read 1" or `R1`) will contain cell barcode and unique molecular identifier (UMI) sequences for mapping reads back to a given cell and a given RNA molecule, repsectively; the second read ("read 2" or `R2`) will contain the actual sequence of the original RNA molecule. Because of this, both the `R1` and `R2` FASTQ files are required for the `scrnaseq` pipeline.

In addition, the alignment software (`cellranger`, `STARSolo`, etc.) can be provided with an "expected cells" value for each sample to guide it on approximately how many cells it can expect to detect in a sample. This can help to improve the software determine what is a cell and what is background noise, particularly for samples with poorer quality and higher levels of ambient RNA.

#### Parameters

The pipeline can be configured with a range of parameters to help process different types of single cell data. Of most importance are:

- Selection of an alignment tool
- Specification of the scRNAseq protocol used
- Specification of a genome reference to use

##### Alignment tool selection

The pipeline supports four aligners:

- `cellranger`: 10X's proprietary tool; **we use this for all 10X datasets**
- `star`: An open-source alignment tool that is also the basis of 10X's `cellranger`
- `kallisto`: *Pseudoalignment* tool for fast alignment of sequences
- `simpleaf`: Based on the *pseudoalignment* tool `salmon`; also for fast alignment of sequences

For all 10X datasets, we always process the data through 10X's proprietary `cellranger` software. However, both the `star` and `kallisto` aligners can be used with 10X, DropSeq and SmartSeq datasets, and `simpleaf` is capable of processing both 10X and DropSeeq data.

It is important to note that `kallisto` and `simpleaf` are based on *pseudoalignment*, which matches sequencing reads against a pre-built database. It is much faster than traditional alignment, but is incapable of discovering novel transcripts.

##### scRNAseq protocol

Single cell sequencing technologies are constantly evolving and improving, and the chemistries and protocols used by different platforms and versions of the same platform will differ from one another. Therfore, the pipeline needs to know what scRNAseq protocol was used in order to properly process the data. For 10X data being processed through `cellranger`, it is recommended to simply leave this set to `auto` for automatic detection by `cellranger`, and this is how we run the pipeline for this kind of data. The [pipeline documentation](https://nf-co.re/scrnaseq/4.1.0/docs/usage/#support-for-different-scrna-seq-protocols) contains in-depth information on what protocols can be used with this pipeline.

##### Genome reference

All sequencing data requires some reference index to compare the data to in order to quantify the number of reads originating from each gene in each cell. Each alignment tool has its own index format, and so the pipeline requires different information about the index and/or the underlying reference genome sequence for each tool.

For `cellranger` and `simpleaf`, either a pre-generated index can be provided, or a reference genome FASTA file can be provided and the pipeline will automatically generate the index for you. For `star` and `kallisto`, you must provide a pre-generated index.

#### Outputs

The final output of this pipeline is a **count matrix**. This is essentially a table that counts how many sequencing reads mapped to each gene or transcript within each cell. The pipeline exports this matrix in a few different formats for use with different downstream tools. This includes:

- `AnnData/H5AD`: For use with the Python package `AnnData`
- `Seurat/RDS`: For use with the R package `Seurat`
- `SCE/RDS`: For use with the R package `SingleCellExperiment`

In particular, we use the `Seurat/RDS` formatted data for our downstream `scrnavigator-nf` pipeline (part of our advanced analysis tier), as `Seurat` is a mature and well-established framework for single cell RNA analysis.

#### Further reading

The `nf-core/scrnaseq` pipeline is extensively documented on the nf-core website: [https://nf-co.re/scrnaseq](https://nf-co.re/scrnaseq).

The pipeline code base is located on GitHub: [https://github.com/nf-core/scrnaseq](https://github.com/nf-core/scrnaseq).
