### scrnavigator-nf

The `scrnavigator-nf` pipeline was developed by the Sydney Informatics Hub as a best-practice workflow for downstream processing of single cell RNA sequencing data that has been initally pre-processed by the [`nf-core/scrnaseq`]((https://nf-co.re/scrnaseq)) pipeline. The pipeline takes the count matrix generated by the `nf-core/scrnaseq` pipeline and does the following:

1. Quality control and filtering
2. Cell clustering
3. Doublet detection and filtering
4. Dataset integration
5. Cell type annotation
6. Pseudobulking
7. Differential expression (case vs control)
8. Functional enrichment analysis (FEA)

The pipeline is designed to be run iteratively. An initial run of just the quality control stage can be used to determine filtering thresholds. Then the dataset can be filtered and integrated in a second pass. Cell type annotation is optional; if performed, the annotations can be inspected and cell groupings can be determined for downstream pseudobulking, differential expression and functional enrichment analysis (FEA).

#### Inputs

At the very minimum, the pipeline requires for each sample:

- A sample name
- A path to an RDS file containing a Seurat object

RDS files are a format for storing object data from the R programming language. `Seurat` is an R library that provides a mature and well-established framework for single cell RNA sequencing analysis. In particular, this pipeline was designed to process a Seurat object containing the filtered count matrix data produced by the `nf-core/scrnaseq` pipeline. The pre-filtering done by that pipeline removes background noise, i.e. reads associated with cell barcodes that originated from ambient RNA rather than true captured cells.

With this minimal information, the pipeline will generate some quality control metrics and integrate all of the provided samples together into a single dataset. It will also attempt to automatically annotate cell types if working with human samples. However, typically you will want to provide some additional metadata, such as case/control status, treatment information, or other information that would be useful for grouping samples together for downstream analysis. You can also provide the pipeline with filtering information, such as the minimum and/or maximum numbers of reads and/or genes that a cell should have and the minimum and/or maximum fraction of mitochondrial genes that should be present in a cell. These values can be determined from studying the quality control metrics generated by the initial stage of the pipeline; as stated above, the pipeline is designed to be run iteratively, with several stopping points available for inspecting quality metrics and determining filtering values.

#### Parameters

The pipeline has a wide number of parameters available for influencing clustering, annotation and analysis of your data. The most important of these parameters are:

- Specifying the species being studied
    - Human data can have additional, automatic annotations applied to it ([see below](#cell-type-annotations))
- Selecting clustering resolutions
    - This determines how finely or coarsely the cell clusters are
- Selecting a clustering method
    - One of two clustering methods are available: Leiden and Louvain ([see below](#clustering))
- Providing file paths to external annotation databases (required for non-human species)
- Specifying thresholds for annotating cells and clusters
- Specifying groups for pseudobulking and differential expression analyses
- Specifying p-value and fold-change thresholds for differential expression analyses

The relevance of each of these parameters is discussed in the following sections detailing each step of the analysis pipeline.

#### Analysis details

##### Quality control and filtering

The first step of the pipeline reads in the Seurat object from the input RDS file, performs some pre-processing and data cleaning and produces some quality control metrics. The initial pre-processing step includes adding additional metadata for each sample into their respective Seurat data objects and ensuring that there is a consistent gene naming convention. Genes can either be identified with Ensembl IDs (e.g. `ENSG00000141510`) or HGNC gene symols (e.g. `TP53`).

After pre-processing, some basic quality control metrics are calculated:

- Total read counts per cell
- Total feature (i.e. gene) counts per cell
- The ratio of gene counts to read counts per cell
- Mitochondrial gene fraction per cell

Typically, single cell experiments will be aiming for approximately 20,000 reads per cell on average, although this depends on the complexity of the samples; cells expressing larger numbers of distinct genes will require higher read counts to fully capture their entire transcriptomes. Total gene counts per cell will vary depending on the cell type, but values above 1000 are fairly typical.

The gene count vs read count graphs that are produced should look roughly linear. Poorer quality samples may show lots of variability in gene:read count ratios, low values for either gene or read counts, or additional "clusters" of cells in the graph.

Mitochondrial gene percentage is also a useful metric for determining whether cells are of good quality or not. Dying or lysed cells can typically display high fractions of mitochondrial genes due to their relative protection within the mitochondria. Values above 10% may be indicative of unhealthy or dying cells. However, be aware that this value also varies by cell type, and some cells are expected to have high mitochondrial gene expression than others.

###### TODO: show good vs bad QC plots

Based on the metrics observed from this stage, the filtering thresholds for each sample can be adjusted to ensure only the best quality cells are analysed.

After quality control and filtering, the final step of this initial stage ofthe pipeline is to normalise and scale the count data to account for variability between cells and genes and allow for unbiased comparisons. The process is two-fold:

1. Scale the expression values within each cell to account for the differences in the total gene expression values between cells. This accounts for the larger *apparent* expression values from cells with more total counts.
2. Scale each gene's expression such that across all cells each gene has a mean expression of 0 and a variance of 1. This helps process the data through downstream algorithms like principal components analysis (PCA) which expect data to be scaled like this before-hand.

##### Clustering

Clustering is the process of determining how similar or dissimilar cells are from one another. This is typically calculated based on the normalised expression values of the most variable genes present in the dataset. Genes with very similar gene expression profiles will be clustered together.

Clustering is sensitive to a parameter called the "resolution". Smaller values for this resolution result in larger, coarser clusters, while larger values for the resolution parameter result in smaller, finer clusters. What works best for your dataset will vary depending on how diverse your samples are. Samples with lots of different cell types may require a higher clustering resolution in order to capture the true structure of the sample, while samples of a single cell type may require a much smaller clustering resolution.

In order to guide the selection of this parameter, we do two things. First, we cluster at a wide range of resolutions simultaneously by default. Second, we use a tool called `clustree` to build a graph representation of the clusters and how they change from one resolution to the next. We then select the "best" resolution by observing which resolutions are the most "stable", i.e. the points at which the clusters don't change much from one resolution to the next.

There are two main methods that we can use to cluster cells: "Leiden" and "Louvain". The Leiden algorithm is a newer improvement on the older Louvain algorithm and is generally the recommendation for single cell clustering.

##### Doublet detection

Single cell capture is an imperfect process and often multiple cells will get captured and barcoded together. When two cells are captured together it is called a **doublet**; the more general term for any number of cells captured together is a **multiplet**.

Doublets and multiplets introduce a confounding factor for downstream analyses; if two cells of very different cell types are captured together, the resulting gene expression profile for that barcode will be an average of the two cells, appearing to come from some (ficticious) intermediate cell type. Therefore, detecting doublets is important for ensuring high quality analysis results.

In this pipeline, we use the R package `DoubletFinder`, which essentially simulates doublets from your data and looks for similarities between the artificial doublets and the actual cell data; clusters of cells that closely align with lots of artificial doublets are deemed to be doublets themselves and can be removed from the dataset.

##### Integration

Up until this point, each sample has been processed individually. During integration, we merge all of the samples into a single dataset. This lets us do downstream analysis such as looking for differentially expressed genes and enriched functional gene programs. However, simply merging the datasets together isn't enough. Differences between the samples, such as slight differences in how each sample was processed and how many reads each sample received during sequencing will cause "batch effects", where cells will likely cluster together based on sample of origin rather than cell type and treatment conditions. This means that our merged dataset can't be analysed without first correcting for these batch effects. There are different approaches to correcting for batch effects, but the most common method - which is used by Seurat in this pipeline - is to look for similarities between cells from different batches and use these as so-called "anchors". The differences between these anchor cells are used to correct the entire dataset. Ideally, the result of this correction is a dataset that looks well "mixed", i.e. the cells from each batch will overlap within each cluster, and you should see few or no clusters that are solely from one sample or another.

###### TODO: show batch effect vs integrated data

##### Cell type annotations

A typical use-case for single cell sequencing data is to analyse differences between or within cell types. For example, you may be interested in the differential expression of genes between B and T cells in a given sample, or you may be interested in the differential expression of genes within fibroblasts when treated with a certain drug compared to control samples. The `scrnavigator-nf` pipeline is able to annotate your cells with predicted cell types and (optionally) cell cycle phases using both public databases and user-supplied marker genes. Currently, only human samples can be automatically annotated with cell types from the Human Primary Cell Atlas (HPCA) database; other species require a compatable database to be manually specified. Additionally, if you have provided us with a list of cell types and associated marker genes, we will have provided these to the pipeline to perform cell type scoring for each custom cell type.

Once cells have been analysed, we also annotate the entire cluster using a semi-automated approach. We look for the most abundant predicted cell type in a given cluster, and if the proportion of that cell type is higher than some threshold, we assign that cell type to that cluster; otherwise, the cluster is considered "ambiguous". This automated cluster annotation is written to the final pipeline report and can be manually inspected. This way, we can override the automated decision with a manual cluster annotation if desired.

##### Pseudobulking and differential expression analysis

There are a few different approaches to performing differential expression analysis on single cell sequencing data. One is to treat each cell as a separate "sample" and perform regular differential expression using the entire dataset. However, this has a significant flaw: cells are not independent of one another, and therefore violate the typical assumptions made by the underlying statistical models for differential expression. This means that significance tests can be severely biased and may produce more false positives than expected.

A very common approach to solving this issue is "pseudobulking". This approach aggregates the expression of all of the cells within each cell type in a sample together, treating them as a single sample. This is essentially equivalent to having sorted the cells by cell type and then performing bulk RNA sequencing, hence the term "pseudobulking".

This pipeline allows the user to define a set of cell annotations and metadata fields to group by when performing pseudobulking. For example, if we want to compare a particular cell type between tumor samples and healthy tissue samples, we can pseudobulk by the automated cluster annotations and a "tumor" metadata field. The result will be a dataset with up to `n × p` "samples", where `n` is the number of original samples and `p` is the number of distinct cell types in the dataset. One of these new pseudobulk groups might be `sample1_B-cell_positive` and another might be `sample2_B-cell_negative`, with `_positive` and `_negative` referring to each original sample's respective tumor status. In downstream differential expression analysis, we could then compare all `_B-cell_positive` samples against all `_B-cell_negative` samples to see how B-cell gene expression differs between tumor samples and healthy tissue.

In this pipeline, we are able to define any number of case-vs-control comparisons like this to make. As long as we have, at the very minimum, 2 samples from each pseudobulked group to compare (but ideally many more!), we can perform a differential expression analysis between those two groups. Note that there are a few caveats to this:

1. Smaller sample sizes will be underpowered and will struggle to find meaningful differences between groups. While technically 2 samples is the minimum required for these analyses, ideally you will have many more samples. The ideal number for an experiment will vary depending on the typical expression level of a gene and how subtle a change you expect to find.
2. The more comparisons that you make, the more false positives that you will expect to find. This is the multiple testing problem: if you consider all results with a p-value of less than 0.05 to be significant, then even in an experiment with no true positive results, you will expect to find around 5% of your results to have an erroneously "significant" p-value. We correct for this by applying a **false discovery rate** (FDR) p-value correction to **all** of the differential expression tests performed. Because of this, it is often better to make as few comparisons as is required for your experimental question, so as to avoid generating too many false positive results.

##### Functional enrichment analysis

Once your data has been pseudobulked and analysed for differentially expressed genes, we run the results through two types of **functional enrichment analysis** (FEA) - i.e. techniques that look for **gene pathways** that are significantly enriched for up- and down-regulated genes in your dataset. The two techniques that we use are Gene Set Enrichment Analysis (GSEA) and Over-Representation Analysis (ORA). Both methods have a similar goal of identifying enrichment of differentially-expressed genes within functional pathways, although they go about this in slightly different ways and can therefore produce somewhat different results.

GSEA works by looking at the overall distribution of your differential expression results. All of the genes are first ranked by their fold-change values (including all of the non-significant genes). Then, for each gene set that is defined (e.g. gene ontology pathways or KEGG pathways), the algorithm looks for whether those genes are clustered together at the top or the bottom of that ranked list - if so, it indicates that the gene set is enriched for up- or down-regulated genes, respectively.

On the other hand, ORA works by first subsetting your data to the **significantly** differentially expressed genes. Then, for each gene set, it looks to see whether there are more differentially expressed genes within that gene set than you would expect to occur by random chance. If so, it suggests an enrichment within that gene set.

Note that GSEA naturally returns an indication of the **direction** of regulation for the gene set, i.e. whether it is being up- or down-regulated. ORA, however, does not: it only indicates whether the gene set is enriched for differentially expressed genes. When using ORA, you will need to look at the individual genes within each gene set of interest to determine how they are being regulated.

#### Outputs

The `scrnavigator-nf` pipeline will output the following folder structure, assuming all of the above steps have been performed:

- `report`: This contains the final pipeline report, including all QC plots, differential expression tables and functional enrichment analysis plots.
- `qc`: This contains all the initial quality control results.
    - `qc/<SAMPLE>/preprocess`: The initial pre-processed Seurat data is within this folder.
    - `qc/<SAMPLE>/filter`: The QC plots and the filtered Seurat data is here.
    - `qc/<SAMPLE>/cluster`: The clustered Seurat data and associated plots.
    - `qc/<SAMPLE>/doublets`: The Seurat data with doublets removed.
- `integration`: This contains all results from the integration step.
- `annotation`: This contains all annotation results.
    - `annotation/cell_cycle`: Cell cycle annotation results.
    - `annotation/db`: Automated annotation from HPCA (human data) or other external databases.
    - `annotation/custom`: Custom gene program annotation results.
    - `annotation/clusters`: Cluster annotation results.
- `analysis`: This contains all differential expression and FEA results.
    - `analysis/pseudobulk`: This contains the pseudobulked Seurat data.
    - `analysis/differential_expression`: All differential expression results, including a single, combined CSV file containing all comparison results.
    - `analysis/fea/gsea`: All GSEA results and plots.
    - `analysis/fea/ora`: All ORA results and plots.

#### Further reading

The pipeline code base is located on GitHub: [https://github.com/Sydney-Informatics-Hub/scrnavigator-nf](https://github.com/Sydney-Informatics-Hub/scrnavigator-nf).
